<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mir-PC" ignored="0" name="Default test(failed)" tests="3" failures="1" timestamp="06 Jul 2019 19:20:58 GMT" time="0.054" errors="0">
  <testcase name="testA1" time="0.014" classname="com.qtpselenium.core.ddf.testcases.DummyTestA">
    <failure type="java.lang.AssertionError" message="Force to fail">
      <![CDATA[java.lang.AssertionError: Force to fail
at com.qtpselenium.core.ddf.testcases.DummyTestA.testA1(DummyTestA.java:11)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testA1 -->
  <testcase name="testA2" time="0.0" classname="com.qtpselenium.core.ddf.testcases.DummyTestA">
    <skipped/>
  </testcase> <!-- testA2 -->
  <testcase name="testA3" time="0.0" classname="com.qtpselenium.core.ddf.testcases.DummyTestA">
    <skipped/>
  </testcase> <!-- testA3 -->
</testsuite> <!-- Default test(failed) -->
